name: app
version: 0.1.0.0
synopsis: "Sample miso app"
category: Web

dependencies:
  - base
  - ghc-typelits-natnormalise
  - containers

# Hpack generates .cabal version automatically.
#
library:
  source-dirs: lib
  language: GHC2024

tests:
  spec:
      language: GHC2024
      cpp-options: -DTest
      main: Spec.hs
      source-dirs:
          - test
          - lib
      dependencies: 
        - tasty
        - tasty-hunit
        - tasty-hedgehog
        - hedgehog
        - template-haskell

executables:
  app:
    main: Main.hs
    source-dirs: app
    language: GHC2024
    ghc-options: -threaded
    dependencies:
      - app
      - gloss

